- name: Oracle Playbook Startup Time for all databases 
  hosts: oracle
  become: yes
  become_user: oracle
  become_method: sudo 
  become_flags: -i
  vars:
    oratab_path: /etc/oratab
    sql_command: " SELECT host_name, instance_name,TO_CHAR(startup_time, 'DD-MM-YYYY HH24:MI:SS') startup_time,FLOOR(sysdate-startup_time) days FROM sys.v_$instance; "
    output_file: /tmp/db_content.txt

  tasks:
    - name: Get list of Oracle instances from oratab file
      shell: "grep -v ^# {{ oratab_path }} | cut -d: -f1"
      register: sids_list
    - name: Run SQL*Plus command
      command: "sqlplus -S / as sysdba << EOF \n {{ sql_command }} \n EOF"
      register: sql_output
      loop: "{{ sids_list.stdout_lines }}"
      changed_when: false
    - name: Display Oracle SQL command results
      debug:
        var: sql_output
      when: sql_output is defined

